// PAGES
export const FETCH_PAGES = 'FETCH_PAGES';
export const FETCH_PAGES_FULFILLED = 'FETCH_PAGES_FULFILLED';
// PROJECTS
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_FULFILLED = 'FETCH_PROJECTS_FULFILLED';
export const FETCH_SINGLE_PROJECT = 'FETCH_SINGLE_PROJECT';
export const FETCH_SINGLE_PROJECT_FULFILLED = 'FETCH_SINGLE_PROJECT_FULFILLED';
// ABOUT - SHELF
export const FETCH_SHELF_ITEMS = 'FETCH_SHELF_ITEMS';
export const FETCH_SHELF_ITEMS_FULFILLED = 'FETCH_SHELF_ITEMS_FULFILLED';
// ABOUT - TRACKS
export const FETCH_TRACKS = 'FETCH_TRACKS';
export const FETCH_TRACKS_FULFILLED = 'FETCH_TRACKS_FULFILLED';
// ABOUT - GITHUB
export const FETCH_GITHUB_EVENTS = 'FETCH_GITHUB_EVENTS';
export const FETCH_GITHUB_EVENTS_FULFILLED = 'FETCH_GITHUB_EVENTS_FULFILLED';